services:
  - type: web
    name: coffee-shop-mgm-sys
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: SERVE_FRONTEND
        value: "true"
      - key: API_URL
        fromService:
          name: coffee-shop-mgm-sys
          type: web
          property: url
      - key: FRONTEND_URL
        fromService:
          name: coffee-shop-mgm-sys
          type: web
          property: url
      - key: CORS_ENABLED
        value: "true"
      - key: CORS_ORIGINS
        fromService:
          name: coffee-shop-mgm-sys
          type: web
          property: url
      - key: VITE_API_URL
        fromService:
          name: coffee-shop-mgm-sys
          type: web
          property: url
        suffix: /api
      - key: VITE_PUBLIC_URL
        fromService:
          name: coffee-shop-mgm-sys
          type: web
          property: url
    healthCheckPath: /api/health
    autoDeploy: true
